### ISSUE TITLE
Ordinals not recognized when preceded by "the"

### ISSUE THREAD

**Issue by jameshaydon** [facebookincubator/duckling#88]
The ordinal 4 is successfully extracted in the examples:
- `debug EN "4th step of the recipe" [This Time, This Ordinal]`
- `debug EN "the 4th step of the recipe" [This Ordinal]`

But an incorrect time entity (and no ordinal) is extracted in the example:
- `debug EN "the 4th step of the recipe" [This Ordinal, This Time]`

**Comment by stopachka** [comment]
Indeed seems like a bug. @jameshaydon feel free to take a stab at changing the rules to support this. Otherwise we will take a look shortly

**Comment by jameshaydon** [comment]
Hi @stopachka 
I'm unsure what sort of change to the rules would achieve this? The rules for plain ordinals are obviously fine, and the rule `Time/EN/Rules.ruleTheDOMOrdinal` is necessary for parsing things like `"the 5th"` as a date. Is there some way of ensuring the ordinal parse will achieve a high enough score in order not to be dropped during the ranking phase in the presence of the `Time` dimension?

**Comment by stopachka** [comment]
Hm, apologies @jameshaydon -- I misunderstood the issue. Will look into it and update you

**Comment by patapizza** [comment]
Hi @jameshaydon, Duckling returns only the top-level tokens, instead of all intermediate matches. As "the 4th" is a valid `Time` based on an `Ordinal`, it only returns the top `Time` token, and not the intermediate `Ordinal` ("4th"). Also Duckling doesn't use sentence-level features, and there might be false positives like for this example. Depending on your use case, you might need to call Duckling multiple times with different dimensions.
